# Generated by Django 6.0.1 on 2026-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="address",
        ),
        migrations.RemoveField(
            model_name="category",
            name="email",
        ),
        migrations.RemoveField(
            model_name="category",
            name="phone",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
